version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: run tests for node.js app
          command: |
            npm install
            npm run test
workflows:
  version: 2
  test:
    jobs:
      - test
